const f = () => {
  

try {
  let a =0;
   //console.log (program)
  console.log ("Program Run successfully ")
  return 
}
catch (err) {
  console.log ("This is an error")
  console.log (prg)
}
  
finally {
  console.log ("i am a good boy")

  // close the file
  // exit the loop
  // write to the log file
}
}

f()
console.log ("end")